export const data = [
    {
        id: 1,
        stateName: "Washington",
        description: "In the 10 years MoneyRates.com has been conducting this study, Washington has topped the list five times for the best states to live in the US. This year, it reclaims the top spot after coming in second last year. Washington is one of eight states with no state income tax. Combine that with the fact that it also has the fourth-highest median income in the nation ($48,140/year) and its underlying strengths are clear. Washington was hit hard in the early stages of the COVID-19, with Seattle one of the first cities in the U.S. to report positive COVID cases. The unemployment rate jumped by 1.3% in the month of March 2020 alone. Two years later, the employment outlook is looking much better. Unemployment continues to go down in Washington. Steady decreases in the past six months have brought that rate down from 4.6% in October 2021 to 4.2% in March of 2022.",
        image: "https://cdn.britannica.com/22/94422-050-29AC90D6/Seattle-Space-Needle.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Washington_in_United_States.svg/300px-Washington_in_United_States.svg.png",    
    },
    {
        id: 2,
        stateName: "North Dakota",
        description: "This is the third straight year North Dakota has made the top ten in this study and, for 2023, it climbed from ninth place all the way to second. While it had the lowest rate of unemployment in the early months of COVID, North Dakota still has a low unemployment rate of 2.9%. One negative should be noted, however: North Dakota ranks third-worst nationally for workplace safety.",
        image: "https://www.visittheusa.com/sites/default/files/styles/4_3_1440x1080/public/images/attraction_image/2020-03/bf22e442-72f3-448e-ae98-26104fc236c3.jpeg?itok=q1284YTR",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/North_Dakota_in_United_States.svg/300px-North_Dakota_in_United_States.svg.png",
    },
    {
        id: 3,
        stateName: "Minnesota",
        description: "After finishing fourth in each of the last two years, Minnesota climbed a notch to third place this year. Its 2.5% unemployment rate is tied for fifth-lowest in the nation. However, Minnesota’s biggest weakness as a place to make a living is a state-income-tax burden that is higher than that of most states.",
        image: "https://www.visittheusa.com/sites/default/files/styles/state_hero_l/public/images/hero_media_image/2017-02/mpls-winter3-Minneapolis-and-Mississippi-River_Web72DPI.jpg?itok=zZZ2OLUH",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Minnesota_in_United_States.svg/300px-Minnesota_in_United_States.svg.png",
    },
    {
        id: 4,
        stateName: "Michigan",
        description: "For the fourth consecutive year, Michigan has made the top 10 — and it has improved its rank in each of those years. Michigan is one of the 10 best states to live in the U.S., and when combined with a median income that is higher than most states, it goes a long way toward making it a good place to make a living.",
        image: "https://i.natgeofe.com/n/b2a5486f-4e08-442a-bad2-284ca2a89870/2CK6FX0_3x2.JPG",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Michigan_in_United_States.svg/300px-Michigan_in_United_States.svg.png",
    },
    {
        id: 5,
        stateName: "Texas",
        description: "Though it dropped a couple of slots after two consecutive third-place finishes, Texas remains a strong place to make a living based on a few factors: No state income tax; More affordable than most states; Workplace safety is better than in most states",
        image: "https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/advisor/wp-content/uploads/2022/08/Image_-_TX_Business_.jpeg.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Texas_in_United_States.svg/300px-Texas_in_United_States.svg.png",
    },
    {
        id: 6,
        stateName: "Illinois",
        description: "In addition to topping the ranking in the initial year of this study (2011), Illinois has made the top 10 in eight out of 10 years. This year, a top-ten ranking for workplace safety is its greatest strength, with the most obvious flaw being that it has one of the highest state income tax burdens for median earners.",
        image: "https://www.state.gov/wp-content/uploads/2022/01/shutterstock_1823564576-scaled.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Illinois_in_United_States.svg/300px-Illinois_in_United_States.svg.png",
    },
    {
        id: 7,
        stateName: "Kansas",
        description: "This is the third time in 10 years Kansas has made the top ten. It has the sixth-lowest cost of living and ties with a few other states for the fifth-lowest unemployment rate of 2.5%",
        image: "https://cdn.britannica.com/00/93900-050-44CC87CF/grasslands-steppes-one-sources-Kansas-air-areas.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Kansas_in_United_States.svg/300px-Kansas_in_United_States.svg.png",
    },
    {
        id: 8,
        stateName: "Tennessee",
        description: "This is the first time Tennessee has made the top ten since 2011, when it also ranked eighth. It has a decent unemployment rate of 3.2%, which puts it in a respectable 18th position when compared to the rest of the states for unemployment rates. Tennessee benefits from both a low cost of living and a relatively low state income tax burden.",
        image: "https://cdn.britannica.com/95/96095-050-3983BE03/Skyline-Cumberland-River-Nashville.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Tennessee_in_United_States.svg/300px-Tennessee_in_United_States.svg.png",
    },
    {
        id: 9,
        stateName: "Colorado",
        description: "This ranking continues a streak of making the top 10 in every year of this study. This year, Colorado benefited from top-10 rankings for affordability and workplace safety. Colorado’s unemployment rate took a hit as a result of COVID and currently sits at 3.7%.",
        image: "https://www.state.gov/wp-content/uploads/2022/01/shutterstock_545718292-scaled.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Colorado_in_United_States.svg/300px-Colorado_in_United_States.svg.png",
    },
    {
        id: 10,
        stateName: "Oklahoma",
        description: "This is Oklahoma’s third time making the top 10, and its first time since 2014. Oklahoma has the third-lowest cost of living and is one of the best states to live in financially. So even though the median income is relatively low, the money goes a long way. Oklahoma also has one of the ten lowest unemployment rates, so the prospects for getting a job there should be relatively good.",
        image: "https://smapse.ru/storage/2018/10/oklahoma-state-university-1024x673.jpg",
        stateMap: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Oklahoma_in_United_States.svg/300px-Oklahoma_in_United_States.svg.png",
    },
]